Show multiple providers for virtual packages
Multiple providers are only shown if the number of providing packages
is less than a set number (default 3). In other cases no individual
providing packages are show, but the number of providing packages is
shown alongside the arrow for the relationship.

diff --git a/debtree b/debtree
--- a/debtree
+++ b/debtree
@@ -75,6 +75,7 @@ with_recommends=1
 with_conflicts=1
 with_vconflicts=""
 with_provides=1
+max_providers=3
 with_versions=1
 show_installed=""
 max_depth=""
@@ -98,6 +99,11 @@ while true; do
 		with_conflicts="" ;;
 	    --no-provides)
 		with_provides="" ;;
+	    --max-providers=*)
+		max_providers=${1#*=}
+		if ! echo $max_providers | grep -q "^[1-9][0-9]*$"; then
+			error "invalid value for option 'max-providers'"
+		fi ;;
 	    --with-suggests|-S)
 		with_suggests=1 ;;
 	    --versioned-conflicts|-VC)
@@ -319,14 +325,21 @@ print_dot_footer() {
 }
 
 print_dot_OR_header() {	
-	local OR_name="$1"
-	local has_inst="$2"
+	local type="$1"
+	local OR_name="$2"
+	local has_inst="$3"
 
 	echo -e "\t$OR_name ["
 	echo -e "\t\tshape = \"record\""
 	if [ "$has_inst" ]; then
-		echo -e "\t\tstyle = \"filled\""
+		if [ $type = P ]; then
+			echo -e "\t\tstyle = \"rounded,filled\""
+		else
+			echo -e "\t\tstyle = \"filled\""
+		fi
 		echo -e "\t\tfillcolor = \"honeydew\""
+	elif [ $type = P ]; then
+		echo -e "\t\tstyle = \"rounded\""
 	fi
 	echo -en "\t\tlabel = \""
 }
@@ -347,9 +360,9 @@ print_dot_OR_main() {
 		echo -n "<$package> ?$package?"
 	elif check_list skip "$package"; then
 		echo -n "<$package> ($package)"
-	elif check_list ended "$package"; then
+	elif [ "$seen" = 2 ] || check_list ended "$package"; then
 		echo -n "<$package> \{$package\}"
-	elif [ "$seen" ] || check_list OR_seen "$package"; then
+	elif [ "$seen" = 1 ]; then
 		echo -n "<$package> [$package]"
 	else
 		echo -n "<$package> $package"
@@ -357,7 +370,8 @@ print_dot_OR_main() {
 }
 
 print_alternatives() {
-	local altrec="$1"
+	local type="$1"
+	local altrec="$2"
 	local package t_altrec first seen
 
 	local OR_name="$(echo "$altrec" | cut -d: -f1)"
@@ -365,13 +379,26 @@ print_alternatives() {
 	local OR_pkgs="$(echo "$altrec" | cut -d: -f3-)"
 
 	first="1"
-	print_dot_OR_header "$OR_name" "$OR_has_inst"
+	print_dot_OR_header $type "$OR_name" "$OR_has_inst"
 	for package in $(echo $OR_pkgs | sed "s/,/ /g"); do
 		# Is this package also part of an earlier set of alternatives?
 		seen=""
-		t_altrec="$(echo "$OR_list" | \
-			    grep -E "(:|,)$package(,|$)" | head -n1)"
-		[ "$t_altrec" = "$altrec" ] || seen="1"
+		if check_list OR_seen "$package"; then
+			seen=1
+		else
+			t_altrec="$(echo "$OR_list" | \
+				    grep -E "(:|,)$package(,|$)" | head -n1)"
+			if [ $type = D ]; then
+				[ "$t_altrec" = "$altrec" ] || seen=1
+			else
+				if [ "$t_altrec" ]; then
+					seen=1
+				else
+					# Not seen; mark as end package
+					seen=2
+				fi
+			fi
+		fi
 
 		print_dot_OR_main "$package" "$seen" "$first"
 		first=""
@@ -604,7 +631,8 @@ process_pseudo() {
 	local dep_tree=$4
 	local predep_OR_name=$5
 	local ptype=$6
-	local prior_OR_name p_package p_provider
+	local prior_OR_name p_package p_provider prov_cnt
+	local OR_pkgs OR_name OR_has_inst OR_has_uninst OR_uninst
 
 	debug 3 "Getting providers for pseudo package '$package'"
 
@@ -618,10 +646,8 @@ process_pseudo() {
 	# Print a dummy providing package if there are multiple; we could
 	# possibly loop and display alternatives if there are not too many
 	# alternative provides
-	if echo "$providers" | grep -q ","; then
-		echo -e "\t$p_package -> \"Pr-$package\" [dir=back,arrowtail=inv,color=green];"
-		echo -e "\t\"Pr-$package\" [shape=point];"
-	else
+	prov_cnt=$(echo "$providers" | sed "s/,/\n/g" | wc -l)
+	if [ $prov_cnt -eq 1 ]; then
 		provider=${providers%% *}
 
 		if check_list skip "$provider"; then
@@ -648,6 +674,53 @@ process_pseudo() {
 			if ! check_list done "$provider" && [ ! "$ptype" = L ]; then
 				process_package $(($level + 1)) $provider "$dep_tree" "" ""
 			fi
+		fi
+	else
+		# If there are multiple providing packages, we do not recurse into them!
+		IFS=,
+		for provider in $providers; do
+			IFS="$IFS_SV"
+			provider=${provider%% *}
+			if [ "$show_installed" ]; then
+				if is_installed $provider; then
+					OR_pkgs="${OR_pkgs:+$OR_pkgs,}$provider"
+					OR_has_inst=1
+				else
+					OR_uninst="${OR_uninst:+$OR_uninst,}$provider"
+					OR_has_uninst=1
+				fi
+			else
+				OR_pkgs="${OR_pkgs:+$OR_pkgs,}$provider"
+			fi
+		done
+		if [ "$show_installed" ] && [ -z "$OR_pkgs" ]; then
+			# If none of the alternatives is installed, show them all
+			OR_pkgs="$OR_uninst"
+			OR_has_uninst=""
+		fi
+
+		# Only show multiple providing packages if there are $max_providers or less
+		# or when restricted to installed packages
+		if [ $prov_cnt -le $max_providers ] || \
+		   ([ "$show_installed" ] && [ "$OR_has_inst" ]); then
+			# Check if we already have these (exact) alternative providers
+			OR_name="$(echo "$OR_virtual_list" | \
+				grep ":$OR_pkgs${OR_has_uninst:+,...}$" | cut -d: -f1)"
+			if [ -z "$OR_name" ]; then
+				OR_virtual_cnt=$(($OR_virtual_cnt + 1))
+				OR_name=virt$OR_virtual_cnt
+
+				debug 3 "Providers: new set '$OR_name' - $OR_pkgs"
+				OR_virtual_list="$OR_virtual_list$OR_name:$OR_has_inst:$OR_pkgs${OR_has_uninst:+,...}$NL"
+			else
+				debug 3 "Providers: matches existing set '$OR_name'"
+			fi
+
+			# Print the arrow now; the record itself is printed later
+			echo -e "\t$p_package -> $OR_name [dir=back,arrowtail=inv,color=green];"
+		else
+			echo -e "\t$p_package -> \"Pr-$package\" [label=\"-$prov_cnt-\",dir=back,arrowtail=inv,color=green];"
+			echo -e "\t\"Pr-$package\" [label=\"...\",style=rounded];"
 		fi
 	fi
 
@@ -775,6 +848,8 @@ package_unknown=""
 package_OR_seen=""
 OR_cnt=0
 OR_list=""
+OR_virt_cnt=0
+OR_virtual_list=""
 
 # Import lists to limit processing:
 # - "skip" packages are completely ignored: nothing is displayed
@@ -827,8 +902,16 @@ if [ -z "$want_dep" ]; then
 	IFS="$NL"
 	for altrec in $OR_list; do
 		IFS="$IFS_SV"
-		print_alternatives "$altrec"
+		print_alternatives D "$altrec"
 	done
+
+	# Print record definitions for alternative provides
+	IFS="$NL"
+	for altrec in $OR_virtual_list; do
+		IFS="$IFS_SV"
+		print_alternatives P "$altrec"
+	done
+	IFS="$IFS_SV"
 
 	# Set shape to diamond for packages whose dependencies we did not
 	# recurse into
