Remove support for printing dependency paths
'aptitude why' does this better.

diff --git a/debtree b/debtree
--- a/debtree
+++ b/debtree
@@ -1,7 +1,7 @@
 #! /bin/bash
 set -e
 
-# debtree version 0.8.1
+# debtree version 0.8.2
 # Copyright 2007-2009 Frans Pop <elendil@planet.nl>
 # This program is free software; you can redistribute it and/or modify it
 # under the terms of the GNU General Public License as published by the Free
@@ -9,7 +9,6 @@ set -e
 # any later version.
 
 # Usage: debtree [options] <package name>
-#        debtree [options] <package name> <dependency>
 
 # In first case the script produces a dot file for processing with 'dot'.
 # Examples: debtree <package> > <package>.dot
@@ -145,10 +144,11 @@ while true; do
 	    *)
 		if [ -z "$requested_package" ]; then
 			requested_package=$1
-		elif [ -z "$want_dep" ]; then
-			want_dep=$1
 		else
-			error "invalid number of arguments"
+			#error "invalid number of arguments"
+			echo "Listing of dependency paths is no longer supported." >&2
+			echo "Use 'aptitude why' instead." >&2
+			exit 1
 		fi
 		;;
 	esac
@@ -600,9 +600,8 @@ process_deps() {
 	local package=$2
 	local deps=$3
 	local dep_type=$4
-	local dep_tree_in=$5
-	local prevdep_OR_name=$6
-	local IFS dep dep_or dep_package dep_tree pkgdep
+	local prevdep_OR_name=$5
+	local IFS dep dep_or dep_package pkgdep
 	local OR_name OR_skip OR_pkgs OR_uninst
 	local OR_has_skip OR_has_inst OR_has_uninst OR_has_other
 
@@ -621,7 +620,7 @@ process_deps() {
 		OR_has_uninst=""
 		OR_has_other=""
 
-		if [ -z "$want_dep" ] && echo $dep | grep -q "|" && \
+		if echo $dep | grep -q "|" && \
 		   ([ "$with_alternatives" ] || [ "$show_installed" ]); then
 			# Gather information about alternatives
 			IFS="|"
@@ -698,7 +697,6 @@ process_deps() {
 		IFS="|"
 		for dep_or in $dep; do
 			IFS="$IFS_SV"
-			dep_tree=$dep_tree_in
 
 			dep_package=${dep_or%% *}
 			debug 3 "Processing dependency '$package'->'$dep_package'"
@@ -715,27 +713,19 @@ process_deps() {
 				continue
 			fi
 
-			dep_tree="$dep_tree -> $dep_package ($dep_type)"
-
-			if [ -z "$want_dep" ]; then
-				if check_list skip "$dep_package"; then
-					add_skipped "$dep_package"
-					continue
-				elif [ $dep_type = C ] && \
-				     [ -z "$with_vconflicts" ] && [ "$pkgdep" ]; then
-					# Skip only unversioned conflicts
-					continue
-				fi
-				print_dot_dependency $package "$OR_name" \
-					$dep_package $dep_type "$pkgdep"
-			elif [ "$dep_package" = "$want_dep" ]; then
-				echo "$dep_tree"
+			if check_list skip "$dep_package"; then
+				add_skipped "$dep_package"
+				continue
+			elif [ $dep_type = C ] && \
+			     [ -z "$with_vconflicts" ] && [ "$pkgdep" ]; then
+				# Skip only unversioned conflicts
 				continue
 			fi
+			print_dot_dependency $package "$OR_name" \
+				$dep_package $dep_type "$pkgdep"
 
 			if check_list done "$dep_package" ||
-			   ([ -z "$want_dep" ] &&
-			    check_list end "$dep_package"); then
+			   check_list end "$dep_package"; then
 				:
 			else
 				# Recurse through dependencies, except for Suggests
@@ -753,8 +743,7 @@ process_deps() {
 					fi ;;
 				    *)
 					if [ $level -lt $max_depth ]; then
-						process_package $(($level + 1)) $dep_package \
-							"$dep_tree" "$OR_name" ""
+						process_package $(($level + 1)) $dep_package "$OR_name" ""
 					else
 						debug 4 "Adding '$dep_package' ($dep_type) to ended (max)"
 						package_ended="$package_ended$NL$dep_package"
@@ -771,9 +760,8 @@ process_virtual() {
 	local level=$1
 	local package=$2
 	local providers=$3
-	local dep_tree=$4
-	local prevdep_OR_name=$5
-	local ptype=$6
+	local prevdep_OR_name=$4
+	local ptype=$5
 	local prior_OR_dep p_package p_provider prov_cnt
 	local OR_pkgs OR_name OR_has_inst OR_has_uninst OR_uninst
 
@@ -808,9 +796,8 @@ process_virtual() {
 			fi
 
 			# Recurse to get dependencies for providing package
-			dep_tree="$dep_tree <- $provider"
 			if ! check_list done "$provider" && [ ! "$ptype" = L ]; then
-				process_package $(($level + 1)) $provider "$dep_tree" "" ""
+				process_package $(($level + 1)) $provider "" ""
 			fi
 		fi
 	else
@@ -951,9 +938,8 @@ find_rdeps() {
 process_package() {
 	local level=$1
 	local package=$2
-	local dep_tree="$3"
-	local prevdep_OR_name="$4"
-	local ptype="$5"
+	local prevdep_OR_name="$3"
+	local ptype="$4"
 	local p pinfo providers deps
 
 	info 2 "Level $level: processing $package ${ptype:+($ptype)}"
@@ -972,12 +958,12 @@ process_package() {
 
 	if [ "$ptype" = B ] || [ "$ptype" = S ]; then
 		if [ $RET -eq 0 ]; then
-			[ "$want_dep" ] || print_dot_header
+			print_dot_header
 		else
 			error "no dependency info found for '$package'"
 		fi
 	else
-		if [ -z "$want_dep" ] && [ $RET -ne 0 ]; then
+		if [ $RET -ne 0 ]; then
 			process_missing $package
 		fi
 	fi
@@ -986,51 +972,49 @@ process_package() {
 	# Mark as done now to prevent recursion loops
 	package_done="$package_done$NL$package"
 
-	# Not sure if we should do this or not when showing dependency paths
 	providers=$(get_deps "$pinfo" Provided-By)
-	if [ -z "$want_dep" ] && [ "$providers" ]; then
+	if [ "$providers" ]; then
 		# For leaf packages we need to check if it was an alternative
 		if [ "$ptype" = L ]; then
 			prevdep_OR_name="$(get_prior_OR_dep $package)"
 		fi
 
 		process_virtual $level $package \
-			"$providers" "$dep_tree" "$prevdep_OR_name" "$ptype"
+			"$providers" "$prevdep_OR_name" "$ptype"
 	fi
 
 	[ ! "$ptype" = L ] || return 0
 
 	if [ "$ptype" = S ]; then
 		deps=$(get_deps "$pinfo" Build-Depends)
-		process_deps $level $package "$deps" B "" ""
+		process_deps $level $package "$deps" B ""
 		deps=$(get_deps "$pinfo" Build-Depends-Indep)
-		process_deps $level $package "$deps" BI "" ""
+		process_deps $level $package "$deps" BI ""
 	fi
 
 	deps=$(get_deps "$pinfo" Pre-Depends)
-	process_deps $level $package "$deps" PD "$dep_tree" "$prevdep_OR_name"
+	process_deps $level $package "$deps" PD "$prevdep_OR_name"
 
 	deps=$(get_deps "$pinfo" Depends)
-	process_deps $level $package "$deps" D "$dep_tree" "$prevdep_OR_name"
+	process_deps $level $package "$deps" D "$prevdep_OR_name"
 
 	if [ "$with_recommends" ]; then
 		deps=$(get_deps "$pinfo" Recommends)
-		process_deps $level $package "$deps" R "$dep_tree" "$prevdep_OR_name"
+		process_deps $level $package "$deps" R "$prevdep_OR_name"
 	fi
 
 	if [ "$with_suggests" ]; then
 		deps=$(get_deps "$pinfo" Suggests)
-		process_deps $level $package "$deps" S "$dep_tree" "$prevdep_OR_name"
+		process_deps $level $package "$deps" S "$prevdep_OR_name"
 	fi
 
 	if [ "$with_conflicts" ]; then
 		deps=$(get_deps "$pinfo" Conflicts)
-		process_deps $level $package "$deps" C "$dep_tree" "$prevdep_OR_name"
+		process_deps $level $package "$deps" C "$prevdep_OR_name"
 	fi
 
 	# Provides and reverse dependencies for the requested package
-	if [ -z "$want_dep" ] && [ $level -eq 1 ] &&
-	   ([ "$with_provides" ] || [ "$show_rdeps" ]); then
+	if [ $level -eq 1 ] && ([ "$with_provides" ] || [ "$show_rdeps" ]); then
 		provides=$(get_deps "$pinfo" Provides | sed "s/ //g; s/,/ /g")
 		if [ -z "$with_provides" ] || [ -z "$provides" ]; then
 			if [ "$show_rdeps" ]; then
@@ -1040,7 +1024,7 @@ process_package() {
 		elif [ "$provides" ]; then
 			# Virtual packages
 			for provided in $provides; do
-				process_virtual $level $provided $package "$dep_tree" "" L
+				process_virtual $level $provided $package "" L
 			done
 			# Installed reverse dependencies for the package and its provides
 			if [ "$show_rdeps" ]; then
@@ -1105,50 +1089,41 @@ if [ "$no_skip" ] && [ "$package_skip" ]; then
 	package_skip=""
 fi
 
-# If a dependency path is asked for, check if the second package exists
-if [ "$want_dep" ]; then
-	if ! grep_avail $want_dep >/dev/null; then
-		error "no dependency info found for '$want_dep'"
-	fi
-fi
-
 # ptype B/S indicates "start" binary/source package
-process_package 1 $requested_package $requested_package "" $ptype
+process_package 1 $requested_package "" $ptype
 
 # For packages we did not yet recurse through, check if they are virtual
 # packages as we want to show the providing package(s)
 info 2 "Processing leaf packages"
 for dep_package in $package_leaf; do
 	if ! check_list done "$dep_package"; then
-		process_package 0 $dep_package "" "" L
+		process_package 0 $dep_package "" L
 	fi
 done
 
-if [ -z "$want_dep" ]; then
-	info 2 "Final processing for graph"
-	# Print record definitions for alternatives
-	IFS="$NL"
-	for altrec in $OR_dep_list; do
-		IFS="$IFS_SV"
-		print_alternatives D "$altrec"
-	done
-
-	# Print record definitions for alternative provides
-	IFS="$NL"
-	for altrec in $OR_virt_list; do
-		IFS="$IFS_SV"
-		print_alternatives P "$altrec"
-	done
+info 2 "Final processing for graph"
+# Print record definitions for alternatives
+IFS="$NL"
+for altrec in $OR_dep_list; do
 	IFS="$IFS_SV"
+	print_alternatives D "$altrec"
+done
 
-	# Set shape to diamond for packages whose dependencies we did not
-	# recurse into
-	for package in $package_ended; do
-		mark_endpackage $package
-	done
+# Print record definitions for alternative provides
+IFS="$NL"
+for altrec in $OR_virt_list; do
+	IFS="$IFS_SV"
+	print_alternatives P "$altrec"
+done
+IFS="$IFS_SV"
 
-	print_dot_footer
-fi
+# Set shape to diamond for packages whose dependencies we did not
+# recurse into
+for package in $package_ended; do
+	mark_endpackage $package
+done
+
+print_dot_footer
 
 
 if [ "$package_skipped" ]; then
