Second version
* Add parameter handling
* Fix getting Pre-Depends
* Add support for Suggests and Conflicts
* Various other changes

diff --git a/dep-tree b/dep-tree
--- a/dep-tree
+++ b/dep-tree
@@ -4,22 +4,70 @@ set -e
 # Usage: dep-tree [-s] <package name>
 #        dep-tree [-s] <package name> <dependency>
 
-# Script produces a dot file for processing with 'dot'
-# Example: dep-tree <package> | dot -Tps | kghostview -
+# In first case script produces a dot file for processing with 'dot'.
+# Examples: dep-tree <package> | dot -Tps | kghostview -
+#           dep-tree <package> | dot -Tpng -o <package>.png
+# In second case it will list the dependency path(s) from the first
+# to the second package.
+# With the -s option "Suggests" are included as well.
 
-# TODO: display "OR" relations
+# TODO
+# - process/display alternatives ("OR" relations)
+# - distinguish meta/pseudo packages
+# - automatically end on packages with a Provides:
 
-# WARNING: with suggests will lead to HUGE results in almost any case
-# Therefore limited to only one level
+# NOTES
+# - Processing of suggests is limited to only one level; doing a full tree
+#   would lead to insane trees for almost any package
+
 with_suggests=""
-if [ "$1" = "-s" ]; then
-	with_suggests=1
-	shift
-fi
+with_recommends=1
+with_conflicts=""
+with_versions=1
+do_rotate=""
+do_condense=""
 
-requested_package=$1
-[ "$requested_package" ] || exit 1
-want_dep=$2
+while true; do
+	case "$1" in
+	    "")
+		break ;;
+	    --no-recommends)
+		with_recommends="" ;;
+	    -S|--with-suggests)
+		with_suggests=1 ;;
+	    -C|--with-conflicts)
+		with_conflicts=1 ;;
+	    --no-versions)
+		with_versions="" ;;
+	    --rotate)
+		do_rotate="1" ;;
+	    --condense)
+		do_condense="1" ;;
+	    -*)
+		echo "unrecognized argument '$1'"
+		exit 1
+		;;
+	    *)
+		if [ -z "$requested_package" ]; then
+			requested_package=$1
+		elif [ -z "$want_dep" ]; then
+			want_dep=$1
+		else
+			echo "Error: invalid number of arguments"
+			exit 1
+		fi
+		;;
+	esac
+	shift
+done
+
+# Don't allow Suggests without Recommends
+[ "$with_recommends" ] || with_suggests=""
+
+if [ -z "$requested_package" ]; then
+	echo "Error: invalid number of arguments"
+	exit 1
+fi
 
 package_done=","
 package_skip=",libc6,libgcc1,libstdc++6,zlib1g,libx11-6,"
@@ -27,34 +75,67 @@ package_end=",debconf,defoma,procmail,gnupg,ucf,x11-common,xbase-clients,xutils,
 IFS_SV="$IFS"
 
 print_dot_header() {
-	echo "digraph $requested_package {"
-	echo -e "\trankdir=LR;"
+	echo "digraph \"$requested_package\" {"
+	[ "$do_rotate" ] || echo -e "\trankdir=LR;"
+	[ -z "$do_condense" ] || echo -e "\tconcentrate=true;"
 }
 print_dot_footer() {
 	echo "}"
 }
 
 print_dot() {
+	local package=$1
+	local package_dep=$2
+	local dep_type=$3
+	local verdep=$4
 	local opts=""
-	case $3 in
-	    P)	opts="${opts:+$opts,}color=red,style=red" ;;
-	    D)	opts="${opts:+$opts,}color=red" ;;
+
+	case $dep_type in
+	    P)	opts="${opts:+$opts,}color=purple,style=bold" ;;
+	    D)	opts="${opts:+$opts,}color=blue" ;;
 	    R)	: ;;
 	    S)	opts="${opts:+$opts,}style=dotted" ;;
+	    C)	opts="${opts:+$opts,}color=red" ;;
 	esac
-	[ -z "$4" ] || opts="${opts:+$opts,}label=\"$4\""
+
+	# Always include versions for versioned conflicts
+	if [ "$verdep" ]; then
+		if [ "$with_versions" ] || [ "$dep_type" = C ]; then
+			opts="${opts:+$opts,}label=\"$verdep\""
+		fi
+	fi
 	[ -z "opts" ] || opts=" [$opts]"
 
 	# Would be nice to suppress double lines for such packages
-	if echo "$package_end" | grep -q ",$2,"; then
-		echo -e "\t\"$2\" [shape = octagon];"
+	if echo "$package_end" | grep -q ",$package_dep," &&
+	   ! echo "$package_done" | grep -q ",$package_dep,"; then
+		echo -e "\t\"$package_dep\" [shape = octagon];"
+		package_done="$package_done$package_dep,"
 	fi
 
-	echo -e "\t\"$1\" -> \"$2\"$opts;"
+	echo -e "\t\"$package\" -> \"$package_dep\"$opts;"
 }
 
 grep_avail() {
-	grep-aptavail -XP $1 -s $2 | sed "s/^[^:]*: //"
+	local pinfo
+	local fields="Package,Pre-Depends,Depends,Recommends,Suggests,Provides,Conflicts"
+
+	if ! pinfo="$(grep-available -XP $1 -s $fields)"; then
+		pinfo="$(grep-aptavail -XP $1 -s $fields || true)"
+	fi
+	echo "$pinfo"
+}
+
+get_deps() {
+	echo "$1" | grep "^$2:" | sed "s/^[^:]*: //"
+}
+
+# Convert dependency string a bit for easier parsing:
+# - remove space after ","
+# - remove space before and after "|"
+# - add space after package name if not versioned
+prep_deps() {
+	echo "$@" | sed "s:, :,:g;s: | :|:g;s:\([^) ]\)\(,\||\|$\):\1 \2:g"
 }
 
 process_deps() {
@@ -62,28 +143,25 @@ process_deps() {
 	local deps=$2
 	local dep_type=$3
 	local dep_tree_in=$4
-	local IFS dep dep_or dep_package
+	local IFS dep dep_or dep_package verdep
 	local OR_cnt=0
 
 	IFS=,
 	for dep in $deps; do
 		IFS="$IFS_SV"
+
 		if echo $dep | grep -q "|"; then
 			OR_cnt=$(($OR_cnt + 1))
 		fi
+
 		IFS="|"
 		for dep_or in $dep; do
-			local dep_tree=$dep_tree_in
 			IFS="$IFS_SV"
-			dep_or=${dep_or# }
-			if echo "$dep_or" | grep -q " "; then
-				dep_package=${dep_or%% *}
-				verdep=${dep_or#* }
-			else
-				dep_package=$dep_or
-				verdep=""
-			fi
-			
+			local dep_tree=$dep_tree_in
+
+			dep_package=${dep_or%% *}
+			verdep=${dep_or#* }
+
 			dep_tree="$dep_tree -> $dep_package ($dep_type)"
 
 			if [ -z "$want_dep" ]; then
@@ -101,11 +179,17 @@ process_deps() {
 			    echo "$package_end" | grep -q ",$dep_package,"); then
 				:
 			else
-				# Recurse through dependencies
-				[ "$dep_type" = S ] || process_package $dep_package "$dep_tree"
+				# Recurse through dependencies, except for Suggests
+				# and conflicts
+				case $dep_type in
+				    S|C)
+					: ;;
+				    *)
+					process_package $dep_package "$dep_tree" ;;
+				esac
 			fi
 
-			# Skip alternatives for now
+			# Skip alternatives for now (TODO)
 			break
 		done
 	done
@@ -114,26 +198,47 @@ process_deps() {
 process_package() {
 	local package=$1
 	local dep_tree="$2"
-	local deps
+	local pinfo deps 
 
 	package_done="$package_done$package,"
 
-	# Grepping for pre-depends does not seem to work!
-	#deps=$(grep_avail $package PreDepends)
-	#process_deps $package "$deps" P "$dep_tree"
+	pinfo="$(prep_deps "$(grep_avail $package Pre-Depends)")"
 
-	deps=$(grep_avail $package Depends)
+	deps=$(get_deps "$pinfo" Pre-Depends)
+	process_deps $package "$deps" P "$dep_tree"
+
+	deps=$(get_deps "$pinfo" Depends)
 	process_deps $package "$deps" D "$dep_tree"
 
-	deps=$(grep_avail $package Recommends)
-	process_deps $package "$deps" R "$dep_tree"
+	if [ "$with_recommends" ]; then
+		deps=$(get_deps "$pinfo" Recommends)
+		process_deps $package "$deps" R "$dep_tree"
+	fi
 
 	if [ "$with_suggests" ]; then
-		deps=$(grep_avail $package Suggests)
+		deps=$(get_deps "$pinfo" Suggests)
 		process_deps $package "$deps" S "$dep_tree"
 	fi
+
+	# Eventually the option to include Conflicts should be handled in
+	# process_deps() as we want to include conflicts if they affect
+	# alternative dependencies; example:
+	# apt-cache dotty debconf: debconf-i18n vs. debconf-english
+	#c=$(get_deps "$pinfo" Conflicts)
+	#[ -z "$c" ] || echo "$package conflicts: $c" >&2
+	if [ "$with_conflicts" ]; then
+		deps=$(get_deps "$pinfo" Conflicts)
+		process_deps $package "$deps" C "$dep_tree"
+	fi
+
+	#provides=$(get_deps "$pinfo" Provides)
+	#[ -z "$provides" ] || echo "$package provides: $provides" >&2
 }
 
+## MAINLINE
+
 [ "$want_dep" ] || print_dot_header
+
 process_package $requested_package "$requested_package"
+
 [ "$want_dep" ] || print_dot_footer
