Allow to run only a specific test
Also add option to run tests verbose.

diff --git a/run-tests b/run-tests
--- a/run-tests
+++ b/run-tests
@@ -1,24 +1,41 @@
 #! /bin/bash
 set -e
 
+verbose="-q"
 screen=""
-if [ "$1" = -s ]; then
-	screen=1
-	shift
-fi
-
 web=""
-if [ "$1" = -w ]; then
-	web=1
-	shift
-fi
+test=""
+target=""
 
-target="$1"
+while true; do
+	case "$1" in
+	    "")	break ;;
+	    -s)	screen=1 ;;
+	    -t)	shift; test=$1 ;;
+	    -v) verbose="-v -v -v -v" ;;
+	    -w)	web=1 ;;
+	    -*)
+		echo "Error: unrecognized argument '$1'"
+		exit 1
+		;;
+	     *)
+		if [ -z "$target" ]; then
+			target=$1
+		else
+			echo "Error: invalid number of arguments"
+			exit 1
+		fi
+		;;
+	esac
+	shift
+done
+
 if [ -z "$screen" ]; then
 	if [ -z "$target" ]; then
 		echo "Error: target directory not specified"
 		exit 1
 	fi
+
 	mkdir -p $target
 	if [ "$web" ]; then
 		mkdir -p $target/thumbs
@@ -27,7 +44,9 @@ if [ -z "$screen" ]; then
 		dist=$(apt-cache policy | \
 		       sed -r "/^ [0-9]+ /N; s/^ ([0-9]+) .*a=([^,]*).*/\1 \2/" | \
 		       grep "^[0-9]" | sort -nru | head -n1 | awk '{print $2}')
-		echo "Testset generated $(date -uR) on $arch/$dist" >$target/README
+		if [ -z "$test" ]; then
+			echo "Testset generated $(date -uR) on $arch/$dist" >$target/README
+		fi
 	fi
 fi
 
@@ -64,12 +83,16 @@ test3 debian-installer -b --arch=armel --no-recommends --no-conflicts"
 fi
 
 echo "$testset" | while read outfile package opts; do
+	if [ "$test" ] && [ $outfile != $test ]; then
+		continue
+	fi
+
 	echo "Generating $outfile: $opts $package" >&2
 	if [ "$screen" ]; then
-		./debtree -q $opts $package | dot -Tps | kghostview - &
+		./debtree $verbose $opts $package | dot -Tps | kghostview - &
 		sleep 10
 	else
-        	./debtree -q $opts $package >$target/$outfile.dot
+        	./debtree $verbose $opts $package >$target/$outfile.dot
 		if [ "$web" ]; then
 			for format in ps png svg; do
 				dot -T$format -o "$target/$outfile.$format" \
